import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto md:grid md:grid-cols-2 mt-20 gap-32'>
          <div className="">
              <h1 className='font-black text-4xl py-5 '>I am Samuel Martinez</h1>
              <h3 className='text-blue-500 font-black text-3xl py-2'>Full Stack Developer</h3> 
              <p className=' text-justify'>I am a web developer, specialized in technologies such as Javascript, ReactJs, NextJs, CSS Libraries such as Tailwind, NodeJs, Express, MongoDB, MySQL, Sequelize, interested in working remotely on scalable projects with agile methodologies such as SCRUM and continuously learning without limits. With a few months of experience in freelance projects 
              </p>
              <br/>
              <p className=' text-justify'>
              Since I started studying computer engineering, I have become more and more passionate about the world of technology and its industry. After the degree, I studied some modules about data networks, and for about two years I began to study programming on my own by taking courses on Udemy, watching tutorials on YouTube, and reading the documentation of some technologies
              </p>
          </div>
          <div>
              <img className='max-w-xs rounded-lg'  src="sam.jpg" alt="" />
          </div>
      </main>
    </>
  )
}
